### ISSUE TITLE
Historia de usuario 2

### ISSUE THREAD

**Issue by rodrigo-ramirezd** [isidoraoOo/GRUPO03-2025-PROYISW#3]
### **HU2 - Automatizar la síntesis de la información**

**Descripción:**
**Como** bibliotecóloga, **quiero** que el software VIGIFIA sintetice automáticamente grandes volúmenes de información, **para** agilizar la revisión de las fuentes seleccionadas.

**Criterios de aceptación:**
- **Dado** que se está generando un boletín, **cuando** termine el proceso de selección de fuentes, **entonces** el software debe ser capaz de generar un resumen de cada fuente seleccionada.
- **Dados** los parámetros específicos del boletín, **cuando** se solicite la síntesis de las fuentes seleccionadas, **entonces** el software debe priorizar la información que esté más alineada con los parámetros específicos establecidos, asegurando que los aspectos más relevantes en relacion a dicho enfoque reciban mayor énfasis y profundidas en la síntesis

**Valor para el negocio:**
La generación de resúmenes automáticos permite que los usuarios se enfoquen en analizar la información más significativa, sin la necesidad de revisar manualmente grandes cantidades de información Esto optimiza la productividad, la eficiencia y asegura que el contenido del boletín sea preciso y pertinente, evitando retrasos y mejorando la calidad final.

**Comment by isidoraoOo** [comment]
**Título:** HU02 - Optimización del tiempo de generación de los boletines

**Descripción**:
**Como** dirección de FIA **quiero** reducir de manera considerable el tiempo actual de creación de los boletines **para** mejorar la eficacia del proceso.

**Criterios de aceptación:**
- **Dado** la implementación del sistema de soporte,  **cuando** se ingrese una nueva solicitud para generación del boletín con la información requerida  **entonces** este estará disponible para su visualización en menos de un mes.

**Valor para el negocio**
La experiencia del usuario mejora al evitar desfases entre la solicitud del boletín y su publicación, lo que contribuye de manera significativa a la comunidad.
