### ISSUE TITLE
Historia de usuario 3

### ISSUE THREAD

**Issue by rodrigo-ramirezd** [isidoraoOo/GRUPO03-2025-PROYISW#4]
### HU3 -  Selección de fuentes

**Descripción:**
**Como** miembro de la dirección, **quiero** poder solicitar una selección de fuentes e ingresar parámetros específicos que describan el tema del boletín a generar, **para** que el software busque automáticamente las fuentes más relevantes y pertinentes para el contenido del boletín.

**Criterios de aceptación:**
- **Dada** la solicitud de una selección, **cuando** se ingresan los parámetros específicos a la plataforma, **entonces** el software debe mostrar una vista previa de los rangos de similitud que considerará para cada parámetro en la búsqueda.

- **Dada** la búsqueda automátizada, **cuando** el software seleccione las fuentes más relevantes, **entonces** almacena en el sistema un listado de fuentes seleccionadas basado en su nivel de pertinencia para con los parámetros ingresados.

**Valor para el negocio:**
La automatización del proceso de búsqueda conlleva la disminución del tiempo que toma la generación de un boletín y la disminución de la intervención humana, lo que estandariza el criterio de selección, mejora su precisión, y optimiza el proceso.
Al permitir que el software seleccione automáticamente las fuentes más relevantes en función de parámetros específicos, se reduce el tiempo que los miembros de la FIA dedicaban a realizar este proceso de forma manual. Esto acelera la generación de boletines, lo que resulta en una mayor eficiencia operativa y permite a FIA cumplir con las solicitudes en tiempos razonables.
El estandarizar los criterios de selección en el software, por otra parte, mejora la calidad del repertorio seleccionado, en cuanto la selección ya no depende de criterios personales de múltiples personas, sino que de criterios previamente definidos. Esto permite que los boletines se alineen de mejor manera con las expectativas ministeriales.

**Comment by niakito** [comment]
### HU3 - Configuración de parámetros de selección

**Descripción:**
Como miembro de la dirección, quiero poder ingresar parámetros específicos a una instancia de selección por cada solicitud, para que el software busque automáticamente las fuentes más relevantes y pertinentes para el boletín solicitado.

**Criterios de aceptación:**
- Dada la creación de una instancia, cuando se ingresan los parámetros específicos a la plataforma, entonces el software debe mostrar una vista previa de los rangos de similitud que considerará para cada parámetro.

- Dada la búsqueda automática, cuando el software seleccione las fuentes más relevantes, entonces entrega al usuario un listado de fuentes seleccionadas basado en su nivel de pertinencia para con los parámetros ingresados.

**Valor para el negocio:**
La automatización del proceso de búsqueda conlleva la disminución del tiempo que toma el proceso de generación de un boletín y la disminución de la intervención humana, lo que estandariza el criterio de selección, mejora su precisión, y optimiza el proceso.
Al permitir que el software seleccione automáticamente las fuentes más relevantes en función de parámetros específicos, se reduce el tiempo que los miembros de la FIA dedicaban a realizar este proceso de forma manual. Esto acelera la generación de boletines, lo que resulta en una mayor eficiencia operativa y permite a FIA cumplir con las solicitudes en tiempos razonables.
El estandarizar los criterios de selección en el software, por otra parte, mejora la calidad del repertorio seleccionado, en cuanto la selección ya no depende de criterios personales de múltiples personas, sino que de criterios previamente definidos. Esto permite que los boletines se alineen de mejor manera con las expectativas ministeriales.
